# Ejercicio 1: Operaciones Básicas con NumPy

**Objetivo:** Familiarizarse con la creación y manipulación de arrays en NumPy.

**Librería:** `numpy`

In [1]:
# Importar NumPy
import numpy as np

**1. Crea un array NumPy 1D con números del 0 al 9.**

In [2]:
# Solución
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


**2. Crea una matriz NumPy 2D de 3x3 con valores aleatorios entre 0 y 1.**

In [3]:
# Solución
matriz_aleatoria = np.random.rand(3, 3)
print(matriz_aleatoria)

[[0.73275435 0.71305045 0.65593867]
 [0.18419559 0.60846697 0.53843569]
 [0.6080983  0.3335731  0.84145269]]


**3. Crea un array NumPy 1D con 10 ceros y otro con 10 unos.**

In [4]:
# Solución
array_zeros = np.zeros(10)
array_ones = np.ones(10)
print("Array de ceros:", array_zeros)
print("Array de unos:", array_ones)

Array de ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array de unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**4. Dado el array `a = np.array([1, 5, 2, 9, 10, 15, 8])`, selecciona los elementos mayores que 5.**

In [5]:
# Solución
a = np.array([1, 5, 2, 9, 10, 15, 8])
elementos_mayores_5 = a[a > 5]
print(elementos_mayores_5)

[ 9 10 15  8]


**5. Crea dos matrices 2x2 (`A` y `B`) y calcula:**
* La suma elemento a elemento ($A + B$).
* La multiplicación elemento a elemento ($A * B$).
* La multiplicación matricial ($A @ B$ o `np.dot(A, B)`).

**6. Calcula la media, mediana y desviación estándar del array `a` del punto 4.**

Media: 7.142857142857143
Mediana: 8.0
Desviación Estándar: 4.5175395145262565
